const ActionTypes = {
  ADD_EVENT: 'ADD_EVENT',
  TOGGLE_EVENT: 'TOGGLE_EVENT',

  FETCH_WEATHER_REQUEST: 'FETCH_WEATHER_REQUEST',
  FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
  FETCH_WEATHER_FAILURE: 'FETCH_WEATHER_FAILURE',
};

export default ActionTypes;
